### ISSUE TITLE
IM unaccessible due to SSL error if using java-1.7.0-openjdk

### ISSUE THREAD

**Issue by swevm** [jonasrosland/vagrant-scaleio#13]
After lots of testing back and forth not understanding why I couldn´t access IM webui I finally figured out how to solve the problem. Every time I tried to access it Chrome displayed a Connection_Closed message. Same with Safari. Same configuration worked a couple of weeks ago.

Without knowing exactly what´s going on. Here´s my thought. Safari and Chrome is trying to negotiate a stronger encryption than java 1.7.0 support. Found a couple of forums that indicated java 1.7.0 only support 128-bit while 1.8.0 support 256-bit AES.

Upgrading from Java 1.7.0 JDK to Java 1.8.0 JDK fixed the problem.
Only change needed  to resolve this issue is to change line 61 in scripts/mdm1.sh to point to java.1.8.0-openjdk.

Will add a pull later as I need to do a clean clone of this repo first.

One weird thing though is. ScaleIO gateway IM do not depend on java version being 1.8*

Below is the error thrown by IM webapp for every https access:
Sep 05, 2015 4:15:11 PM org.apache.tomcat.util.net.NioEndpoint$SocketProcessor doRun
SEVERE:
java.lang.RuntimeException: java.security.KeyException
        at sun.security.ssl.Handshaker.checkThrown(Handshaker.java:1345)
        at sun.security.ssl.SSLEngineImpl.checkTaskThrown(SSLEngineImpl.java:519)
        at sun.security.ssl.SSLEngineImpl.readNetRecord(SSLEngineImpl.java:799)
        at sun.security.ssl.SSLEngineImpl.unwrap(SSLEngineImpl.java:767)
        at javax.net.ssl.SSLEngine.unwrap(SSLEngine.java:624)
        at org.apache.tomcat.util.net.SecureNioChannel.handshakeUnwrap(SecureNioChannel.java:335)
        at org.apache.tomcat.util.net.SecureNioChannel.handshake(SecureNioChannel.java:193)
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1712)
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoint.java:1695)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.security.ProviderException: java.security.KeyException

**Comment by jonasrosland** [comment]
Thanks for the find @swevm!
